
# 你的名字
alternate: Zhang tuo' blog

# 这里一般不改，如果想将 css，js，图片这些静态资源放在自己的 git 上通过 cdn 加速访问的话可以将后面的注释打开
statics: / #//cdn.jsdelivr.net/gh/username/RepositoryName@latest/
css: css
js: js
images: images

# 是否显示页面加载动画 loading-cat
loader:
  start: false # 当初次打开页面时，显示加载动画
  switch: false # tab 切换到其他页面时，显示加载动画

# 自定义菜单列表，friends 需要在 source 目录下建立对应的文件夹 about 和 link 同理，可以参考 /themes/shoka/example/source/friends 下的结构
# 文档地址：https://shoka.lostyu.me/computer-science/note/theme-shoka-doc/config/#% E8%8F%9C% E5%8D%95% E4% B8%8E% E7% A4% BE% E4% BA% A4% E6%8C%89% E9%92% AE
menu:
  首页: / || home
  归档: /archives/ || list-alt
  分类: /categories/ || th
  标签: /tags/ || tags
  friends: /friends/ || heart

# 头像下面的小图标，点击可以跳转到相关平台的个人主页
social:
  github: https://github.com/zhangtuo723 || github || "#191717"

# 侧边栏配置
sidebar:
  position: left #侧边栏位置，right 会将头像和菜单移到右边
  avatar: pic.png #头像文件名

# 页脚配置
footer:
  since: 2024 #你的博客的创建年份
  icon:
    name: garden hamster
    # Change the color of icon， using Hex Code.
    color: "#ffc0cb"
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  powered: true

post:
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true

# 文章底部的打赏
reward:
  enable: false #我这里把它关掉了
  account:
    wechatpay: /wechatpay.png
    alipay: /alipay.png
    paypal: /paypal.png

# bgm
audio:
  - title: music
    list:
     - https://music.163.com/#/playlist?id=10009377589